dist: xenial
os: linux
language: python

addons:
  apt_packages:
    - pandoc
    - texlive-full
    - texlive-xetex

install:
  - pip install tox
  - pip install codecov

script:
  - tox -r

jobs:
    include:
        - python: 3.6
          env: TOXENV=py36
        - python: 3.7
          env: TOXENV=py37
        - python: 3.8
          env: TOXENV=py38
        - python: 3.8
          env: TOXENV=style
        - python: 3.8
          env: TOXENV=coverage
