
language: python
sudo: false
before_install:
  - pip install --upgrade pip
install:
  - pip install tox
  - pip install codecov
script:
  - tox -r
matrix:
    include:
        - python: 3.7
          env: TOXENV=py3
        - python: 3.5
          env: TOXENV=py35
        - python: 3.6
          env: TOXENV=py36
        - python: 3.7
          env: TOXENV=py37
        - python: 3.7
          env: TOXENV=style
        - python: 3.7
          env: TOXENV=coverage

after_succes:
    - codecov --token=1f6c7dfe-58e5-4eb2-a97c-d777c58d3195
